### ISSUE TITLE
[Feature] Schedule 수정 및 삭제

### ISSUE THREAD

**Issue by sihyun615** [BE-Friend-Develop-Team/detour#14]
**✨ Feature**

**Description**
일정 수정 및 삭제 기능 구현

**Todo**
- [x] 일정 삭제 기능
- [x] 일정 제목 수정 기능
- [x] 일정 기간 수정 기능
- [x] 일정 메인 이미지 수정 기능
- [x] http 코드 추가

**Reference(Optional)**
일정 메인이미지 부분 코드 수정 필요!
