### ISSUE TITLE
[Refactoring] 마커 리팩토링

### ISSUE THREAD

**Issue by eunsaemsaem** [BE-Friend-Develop-Team/detour#20]
**♻️ Refactoring**

**Description**
마커 관련 코드 리팩토링을 진행합니다. 

**Todo**
- [x] controller에 user 제거
- [x] service에 user와 관련한 불필요한 메서드 삭제
- [x] 전체조회 관련 queryDSL 로직 수정 (전체 조회 시 차단된 마커는 조회되지 않도록)
- [x] place와 관련된 로직 수정
- [x] 전체 조회시 이미지 url이 추가되게
