### ISSUE TITLE
[Feature] Place CRUD 구현

### ISSUE THREAD

**Issue by wondo8449** [BE-Friend-Develop-Team/detour#39]
**✨ Feature**

**Description**
Place와 관련된 기능 구현

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] Place 생성 기능 구현
- [x] Place 조회 기능 구현
- [x] Place 수정 기능 구현
- [x] Place 삭제 기능 구현
