### ISSUE TITLE
[Refactoring] Schedule 관련 리팩토링

### ISSUE THREAD

**Issue by sihyun615** [BE-Friend-Develop-Team/detour#52]
**♻️ Refactoring**

**Description**
Schedule 관련 리팩토링 수행

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] Schedule 날짜 관련 타입을 Date ▶️ LocalDateTime으로 변경
- [x] Schedule 기본 이미지 설정 방식 변경
- [x] DailyPlan URL 수정사항
- [x] Schedule 수정 관련 중복 코드를 통합하여 중복 최소화
