### ISSUE TITLE
[Refactoring] 좋아요 관련 리팩토링

### ISSUE THREAD

**Issue by sihyun615** [BE-Friend-Develop-Team/detour#54]
**♻️ Refactoring**

**Description**
좋아요 관련 리팩토링 수행

**Todo**
- [x] 좋아요 객체를 직접 조회하는 방식 대신 존재 여부 확인 쿼리로 최적화
- [x] Like와 연관된 Schedule을 함께 조회하도록 하는 findLikeWithSchedule 생성하여 사용
- [x] 생성일자와 수정일자 추가
