### ISSUE TITLE
[Refactoring] 초대 관련 리팩토링

### ISSUE THREAD

**Issue by sihyun615** [BE-Friend-Develop-Team/detour#56]
**♻️ Refactoring**

**Description**
초대 관련 코드 리팩토링 수행

**Todo**
- [x] existsByScheduleAndUser 생성하여 Invitation 관련 코드 리팩토링하기
- [x] 중복 에러코드 삭제
- [x] ScheduleService에서 Invitation 관련 부분 수정
- [x] findInvitationByScheduleAndUser의 반환타입을 Invitation이 아닌 Optional로 변경
