### ISSUE TITLE
[Feature] 랭킹기능 구현

### ISSUE THREAD

**Issue by LeeChangHyeong** [BE-Friend-Develop-Team/detour#80]
**✨ Feature**

**Description**
한시간마다 최근 한시간 조회수를 확인해서 1등부터 12등까지 출력

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 한시간 마다 db확인해서 hourHits를 체크해서 1등부터 12등까지 들고 옴
- [x] Redis에 랭킹 저장 후 모든 일정의 hourHits 0으로 초기화 
- [x] Redis Ec2랑 연결
- [x] Redis에 저장이 되는지 구현 테스트
