### ISSUE TITLE
[Refactoring] 유저 정보 업데이트 관련 수정

### ISSUE THREAD

**Issue by sihyun615** [BE-Friend-Develop-Team/detour#84]
**♻️ Refactoring**

**Description**
유저 정보 업데이트 관련 수정

**Todo**
- [x] @Valid 어노테이션 추가
- [x] 유저 정보 수정 메서드 내에 중복 확인 코드 추가
- [x] WebSecurityConfig 설정 변경
